/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "connmanagentadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentAdaptor
 */

ConnmanAgentAdaptor::ConnmanAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ConnmanAgentAdaptor::~ConnmanAgentAdaptor()
{
    // destructor
}

void ConnmanAgentAdaptor::Cancel()
{
    // handle method call net.connman.Agent.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void ConnmanAgentAdaptor::Release()
{
    // handle method call net.connman.Agent.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void ConnmanAgentAdaptor::ReportError(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call net.connman.Agent.ReportError
    QMetaObject::invokeMethod(parent(), "ReportError", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

void ConnmanAgentAdaptor::RequestBrowser(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call net.connman.Agent.RequestBrowser
    QMetaObject::invokeMethod(parent(), "RequestBrowser", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

QVariantMap ConnmanAgentAdaptor::RequestInput(const QDBusObjectPath &in0, const QVariantMap &in1)
{
    // handle method call net.connman.Agent.RequestInput
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "RequestInput", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QDBusObjectPath, in0), Q_ARG(QVariantMap, in1));
    return out0;
}

