/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbus_fi.w1.wpa_supplicant1.Interface.h"

/*
 * Implementation of interface class FiW1Wpa_supplicant1InterfaceInterface
 */

FiW1Wpa_supplicant1InterfaceInterface::FiW1Wpa_supplicant1InterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1InterfaceInterface::~FiW1Wpa_supplicant1InterfaceInterface()
{
}

/*
 * Implementation of interface class FiW1Wpa_supplicant1InterfaceP2PDeviceInterface
 */

FiW1Wpa_supplicant1InterfaceP2PDeviceInterface::FiW1Wpa_supplicant1InterfaceP2PDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1InterfaceP2PDeviceInterface::~FiW1Wpa_supplicant1InterfaceP2PDeviceInterface()
{
}

/*
 * Implementation of interface class FiW1Wpa_supplicant1InterfaceWPSInterface
 */

FiW1Wpa_supplicant1InterfaceWPSInterface::FiW1Wpa_supplicant1InterfaceWPSInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

FiW1Wpa_supplicant1InterfaceWPSInterface::~FiW1Wpa_supplicant1InterfaceWPSInterface()
{
}

